version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto17

    build:
        commands:
            - echo "starting build..."
            - cd smithy-cli
            - ../gradlew clean build
